ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
CHANGE REPLICATION SOURCE TO SOURCE_HOST='mysql_source', SOURCE_PORT=3306, SOURCE_USER='root', SOURCE_PASSWORD='root';
START REPLICA;
